# async def add(x, v):#     return x + v## x = add(3, 4)# print(type(x))'''-----'''from asyncio import sleep, run, create_task, CancelledErrorfrom time import perf_counter## async def add(x, y):#     await sleep(1)#     return x + y### async def main():#     start = perf_counter()##     #Task1#     res1 = create_task(add(10, 20))##     #Task2#     res2 = create_task(add(4000, 1432))##     res = await res1#     print(res)##     res = await res2#     print(res)##     end = perf_counter()##     print(end - start)### if __name__ == '__main__':#     run(main())# cancel error uchunasync def add(x, y):    await sleep(1)    return sum(range(x, y + 1))async def main():    start = perf_counter()    # Task1    res1 = create_task(add(1, 90_000_000))    await sleep(2)    if not res1.done():        res1.cancel()    try:        res = await res1    except CancelledError:        print('vazifa bajarilmadi')    else:        print(res)    end = perf_counter()    print(f'asysn funksiya {end - start:.5f} vaqt oldi!')if __name__ == '__main__':    run(main())